package com.lydia.entity;
// Generated Apr 12, 2018 3:30:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="ujitarobby_attendance_system"
)
public class Role  implements java.io.Serializable {


     private int idRole;
     private String ketRole;
     private Set<Lecturer> lecturers = new HashSet<Lecturer>(0);

    public Role() {
    }

	
    public Role(int idRole) {
        this.idRole = idRole;
    }
    public Role(int idRole, String ketRole, Set<Lecturer> lecturers) {
       this.idRole = idRole;
       this.ketRole = ketRole;
       this.lecturers = lecturers;
    }
   
     @Id 

    
    @Column(name="idRole", unique=true, nullable=false)
    public int getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }

    
    @Column(name="ketRole", length=45)
    public String getKetRole() {
        return this.ketRole;
    }
    
    public void setKetRole(String ketRole) {
        this.ketRole = ketRole;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<Lecturer> getLecturers() {
        return this.lecturers;
    }
    
    public void setLecturers(Set<Lecturer> lecturers) {
        this.lecturers = lecturers;
    }




}


